imports:
  - { resource: ../config/config.yaml }

parameters:
  connection:
    url: '%prestashop_db_url%'

services:
  _defaults:
    public: true
    autowire: true

  Athlan\SymplexPrestahop\Infra\Prestashop\PrestashopProductSource:
    class: Athlan\SymplexPrestahop\Infra\Prestashop\PrestashopProductSource

  Athlan\SymplexPrestahop\Infra\Prestashop\PrestashopConfiguration:
    properties:
      tablePrefix: '%prestashop_table_prefix%'

  Doctrine\DBAL\Connection:
    factory: [ Doctrine\DBAL\DriverManager, getConnection ]
    arguments: ['%connection%', '@Doctrine\DBAL\Configuration']

  Doctrine\DBAL\Configuration:

